name = "SlackThreads"
uuid = "a271ce43-5be6-465b-b549-2328063b090f"
authors = ["Beacon Biosignals, Inc."]
version = "0.1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
julia = "1.6"

[targets]
test = ["Test"]
